#!C:\Python37/python.exe
print("Content-type:text/html\r\n\r\n") 
import cgi
import pymysql
db=pymysql.connect(host="localhost",user="root",password="root",database="b2c")
print("<html>")
print("<head>")
import head
print("</head>")
print("<body>")
import nav
print("<div id='page'>")
print("<div id='bootstrap-touch-slider1' style='max-height:600px' class='carousel bs-slider slide  control-round indicators-line' data-ride='carousel' data-pause='click' data-interval='5000'>")
print("<div class='carousel-inner' role='listbox'>")
print("<div class='item active'>")
##print("<!-- Slide Background -->")
print("<img src='images/slider1.jpg' alt='Bootstrap Touch Slider' class='slide-image' />")
print("<div class='carousel-caption'>")
print("<h3></h3>")
print("<p></p>")
print("</div>")
print("<div class='bs-slider-overlay'></div>")
##print("<!-- Slide Text Layer -->")
print("<div class='slide-text slide_style_right'>")
print("<a href='#add_your_list' class='btn btn-success btn-md' style='' id='slidebtn' data-animation='animated fadeInDown' data-toggle='modal'>Sign Up Here</a>")
print("<a href='#sign_in' class='btn btn-success btn-md' style='' id='slidebtn' data-animation='animated fadeInDown' data-toggle='modal'>Login Here</a>")
print("</div> ")
print("</div>")
print("<div class='item'>")
print("<img src='images/slider2.jpg' alt='Bootstrap Touch Slider'  class='slide-image'/>")
print("<div class='carousel-caption'>")
print("<h3></h3>")
print("<p></p>")
print("</div>")
print("<div class='bs-slider-overlay'></div>")
print("<div class='slide-text slide_style_right'>")
print("<a href='#add_your_list' class='btn btn-success btn-md' style='' id='slidebtn' data-animation='animated fadeInDown' data-toggle='modal'>Sign Up Here</a>")
print("<a href='#sign_in' class='btn btn-success btn-md' style='' id='slidebtn' data-animation='animated fadeInDown' data-toggle='modal'>Login Here</a>")
print("</div>")
print("</div>")
print("<div class='item'>")
print("<img src='images/slider3.jpg' alt='Bootstrap Touch Slider'  class='slide-image'/>")
print("<div class='bs-slider-overlay'></div>")
print("<div class='slide-text slide_style_right'>")
print("<a href='#add_your_list' class='btn btn-success btn-md' style='' id='slidebtn' data-animation='animated fadeInDown' data-toggle='modal'>Sign Up Here</a>")
print("<a href='#sign_in' class='btn btn-success btn-md' style='' id='slidebtn' data-animation='animated fadeInDown' data-toggle='modal'>Login Here</a>")
print("</div>")
print("</div>")
print("</div>")
##<!-- End of Wrapper For Slides -->
#print("</div>")
print("</div>")


print("<div class='container'>")
print("<div class='row '>")
print("<div class='col-md-8 col-md-offset-2 text-center fh5co-heading' id='m_content'>")
print("<h1 style='font-family:Roboto Slab;font-weight:bolder;'>We Support Your Business Growth</h1>")
print("<p style='font-family:Josefin Sans;font-size:16pt;'>Get great local customer entries & enquirers, B2C E-Commerce support your business with multi platform communication modules</p>")
print("</div>")
print("</div>")
print("</div>")





print("</div>")
##<!-- Get Enquiry -->
print("<div class='container'>")
print("<div id='leftSLideBar' class=' hidden-sm navbar-fixed-top'>")
print("<div class='panel panel-default'  >")
print("<div class='panel-leftheading' style='text-align:center;'>")
print("<center><a href='#' ><h3 class='panel-lefttitle' >Get Enquiry&nbsp;&nbsp;&nbsp;&nbsp;</h3></a></center>")
print("</div>")
print("<form action='enquiry_mail.py' method='post'>")
print("<div class='panel-rightbody' >")
print("<div id='page1panel' >")
print("<div class='form-group' >")
print("<input class='form-control input-sm'  name='name' id='inputlg' type='text' placeholder='Name'>")
print("</div>")
print("</div>")	
print("<div id='page1panel' >")
print("<div class='form-group'>")
print("<input class='form-control input-sm' name='mobile' id='inputlg' type='text' placeholder='Mobile No'>")
print("</div>")
print("</div>")
print("<div id='page1panel' >")
print("<div class='form-group'>")
print("<input class='form-control input-block' name='comments' id='inputlg' type='text' placeholder='Comments'>")
print("</div>")
print("</div>")
print("<div style='float:left;width:90%;'>")
print("<button type='submit' class='btn btn-primary btn-sm' style='background-color:#4286f4'>Submit Your Details</button>")
print("</div>")
print("</div>")
print("</form>")
print("<div class='clearfix'></div>")
print("</div>")
print("</div>")
print("</div>")
print("</div>")
print("</body>")
print("</html>")
