print("<script language='javascript' src='js/indexpage.js'></script>")
print("<link href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css' rel='stylesheet' media='all'>")
print("<link href='https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css' rel='stylesheet' media='all'>")
print("<link rel='stylesheet' href='css/style.css'>")
print("<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css'>")
print("<script src='https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script><script src='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js'></script>")
print("<link rel='stylesheet' type='text/css' href='css/jquery.ajaxcomplete.css' />")
print("<script src='js/bootstrap.min.js'></script>")
print("<script type='text/javascript' src='js/jquery.js'></script>")
print("<link href='https://fonts.googleapis.com/css?family=Work+Sans:300,400,500,700,800' rel='stylesheet'>")
print("<link rel='stylesheet' href='css/slideshow.css'>")
print("<link rel='stylesheet' href='css/sidenav.css'>")
print("<link rel='shortcut icon' href='images/favicon.ico' type='image/x-icon'/>")
print("<script src='js/content-change.js'></script>")
print("<link rel='stylesheet' href='//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css'>")
print("<link rel='stylesheet' href='css/style.css'>")
print("<script src='https://code.jquery.com/ui/1.12.1/jquery-ui.js'></script>")
print("<link rel='stylesheet' media='(max-width: 349px)' href='css/xsmobile.css'>")
print("<link rel='stylesheet' media='(min-width: 350px) and (max-width:499px)' href='css/mobile.css'>")
print("<link rel='stylesheet' media='(min-width: 500px)' href='css/custom.css'>")
print("<link href='css/ninja-slider.css' rel='stylesheet' type='text/css' />")
print("<script src='js/ninja-slider.js' type='text/javascript'></script>")
