print("<div>")
print("<nav class='navbar navbar-fixed-top navbar-bootsnipp animate' role='navigation' style='background-color:#4286f4'>")
print("<div class='container'>")
##<!-- Brand and toggle get grouped for better mobile display -->
print("<div class='navbar-header'  style='color:white;'>")
print("<button type='button' class='navbar-toggle'  data-toggle='collapse' data-target='#bs-example-navbar-collapse-2' id='showsearch'>")
print("<span class='sr-only'>Toggle navigation</span>")
print("<span class='icon-bar' style='background-color:white;'></span>")
print("<span class='icon-bar' style='background-color:white;'></span>")
print("<span class='icon-bar'style='background-color:white;'></span>")
print("</button>")
print("<div class='animbrand' id='animbrand' style='margin-left:-7%;margin-top:0.1vh;'>")
print("<a href='customer_homepage.py'><img src='images/logo.png' class='img-rounded' alt='Cinque Terre' ></a>")
print("</div>")
print("</div>")
print("<div class='bsa-apiads hidden-sm hidden-xs'></div>")
##<!-- Collect the nav links, forms, and other content for toggling -->
print("<div class='collapse navbar-collapse' id='bs-example-navbar-collapse-2'>")
print("<ul class='nav navbar-nav navbar-right'>")
print("<li class='' ><a href='customer_homepage.py' class='' data-target='#add_your_list'  onMouseOver='this.style.backgroundColor='#01033D'' onMouseOut='this.style.backgroundColor='#4286f4'' style='color:#fff;'>Home</a></li>")
print("<li class='' ><a href='logout.py' class='' data-target='#add_your_list'  onMouseOver='this.style.backgroundColor='#01033D'' onMouseOut='this.style.backgroundColor='#4286f4'' style='color:#fff;'>Logout</a></li>")
print("</ul>")
print("</div>")
print("</div>")
print("</nav>")
print("</div>")
