print("<div>")
print("<nav class='navbar navbar-fixed-top navbar-bootsnipp animate' role='navigation' style='background-color:#4286f4'>")
print("<div class='container'>")
##<!-- Brand and toggle get grouped for better mobile display -->
print("<div class='navbar-header'  style='color:white;'>")
print("<button type='button' class='navbar-toggle'  data-toggle='collapse' data-target='#bs-example-navbar-collapse-2' id='showsearch'>")
print("<span class='sr-only'>Toggle navigation</span>")
print("<span class='icon-bar' style='background-color:white;'></span>")
print("<span class='icon-bar' style='background-color:white;'></span>")
print("<span class='icon-bar'style='background-color:white;'></span>")
print("</button>")
print("<div class='animbrand' id='animbrand' style='margin-left:-7%;margin-top:0.1vh;'>")
print("<a href='index.py'><img src='images/logo.png' class='img-rounded' alt='Cinque Terre' ></a>")
print("</div>")
print("</div>")
print("<div class='bsa-apiads hidden-sm hidden-xs'></div>")
##<!-- Collect the nav links, forms, and other content for toggling -->
print("<div class='collapse navbar-collapse' id='bs-example-navbar-collapse-2'>")
print("<ul class='nav navbar-nav navbar-right'>")
#print("<li class='' ><a href='customer_homepage.py' class='' data-target='#add_your_list'  onMouseOver='this.style.backgroundColor='#01033D'' onMouseOut='this.style.backgroundColor='#4286f4'' style='color:#fff;'>Home</a></li>"
#print("<li class='' ><a href='logout.py' class='' data-target='#add_your_list'  onMouseOver='this.style.backgroundColor='#01033D'' onMouseOut='this.style.backgroundColor='#4286f4'' style='color:#fff;'>Logout</a></li>"
print("</ul>")
print("</div>")
print("</div>")
print("</nav>")
print("</div>")
print("<div class='modal' id='add_your_list' role='dialog'>")
print("<div class='modal-dialog modal-lg'>")
print("<div class='modal-content' style='background: #000000;'>")
print("<div class='modal-header'>")
print("<button type='button' class='close' data-dismiss='modal'>&times;</button>")
print("<div class='row'>")
print("<div class='col-md-3'>")
print("<h4 class='modal-title'>")
print("<img src='images/logo.png' class='img-responsive' style='width: 15vw; height: 20vh; margin-left: 70%;'></h4>")
print("</div>")
print("<div class='col-md-9'>")
print("<h2 class='pull-right' style='color: #ffc80c; margin-top: %;'> If New User Regsiter Here </h2>")
print("</div>")
print("</div>")
print("</div>")
print("<div class='modal-body'>")
print("<div class='row'>")
print("<div class='col-md-6'>")
print("<form class='form-horizontal' role='form' action='customer_register.py'>")
print("<div class='form-group' >")
print("<label class='col-sm-3 control-label' for='name' style='color: white;'> Name: <span style='color: red;'> * </span>")
print("</label>")
print("<div class='col-sm-9'>")
print("<input type='text' class='form-control' id='cname' name='cname' style='color:white;' placeholder='Your Name' autofocus='' required>")
print("</div>")
print("</div>")

print("<div class='form-group'>")
print("<label class='col-sm-3 control-label' for='pwd' style='color: white;'> Password: <span style='color: red;'></span>")
print("</label>")
print("<div class='col-sm-9'>")
print("<input type='password' class='form-control' id='cpwd' style='color:white;' name='cpwd' placeholder='Your Password' autofocus='' required>")
print("</div>")
print("</div> <br>")

print("<div class='form-group'>")
print("<label class='col-sm-3 control-label' for='phone' style='color: white;'>Mobile <span style='color: red;'> * </span>")
print("</label>")
print("<div class='col-sm-9'>")
print("<input type='text' name='cmobile' class='form-control'  style='color:white;' id='cphone' placeholder='Your Mobile No.' maxlength='10' pattern='[0-9]{10}' required>")
print("</div>")
print("</div><br>")

print("<div class='form-group'>")
print("<label class='col-sm-3 control-label' for='email' style='color: white;'>Email <span style='color: red;'> * </span>")
print("</label>")
print("<div class='col-sm-9'>")
print("<input type='email' name='cemail' class='form-control' style='color:white;' id='cemail' placeholder='Your Email' required>")
print("</div>")
print("</div><br>")
print("</div>")

print("<div class='col-md-6'>")
print("<div class='form-group'>")
print("<label class='col-sm-3 control-label' for='address' style='color: white;'>Address<span style='color: red;'></span>")
print("</label>")
print("<div class='col-sm-9'>")
print("<textarea name='address' class='form-control' id='address' style='color:white;' placeholder='Your Address' required></textarea>")
print("</div>")
print("</div><br>")



print("<div class='form-group'>")
print("<label class='col-sm-3 control-label' for='name' style='color: white;'>City <span style='color: red;'> * </span>")
print("</label>")
print("<div class='col-sm-9'>")
print("<input type='text' class='form-control' id='ccity' style='color:white;' name='ccity' placeholder='Your City' autofocus='' required>")
print("</div><br>")
print("</div>")

print("<div class='form-group'>")
print("<label class='col-sm-3 control-label' for='pincode' style='color: white;'>Pcode <span style='color: red;'> * </span>")
print("</label>")
print("<div class='col-sm-9'>")
print("<input type='text' class='form-control' id='cpincode' style='color:white;' name='cpincode' placeholder='Your Pincode' autofocus='' required>")
print("</div><br>")
print("</div>")

print("<div class='form-group'>")
print("<label class='col-sm-3 control-label' for='cdob' style='color: white;'>DOB <span style='color: red;'> * </span>")
print("</label>")
print("<div class='col-sm-9'>")
print("<input type='date' class='form-control' style='color:white;' id='cdob' name='cdob'  required>")
print("</div><br>")
print("</div><br><br>")

print("<div class='form-group'>")
print("<div class='text-center'>")
print("<input type='submit' class='btn btn-success btn-sm' value='Submit' style='margin-left: 27%; margin-top: %;'>")
print("</div>")
print("</div>")

print("</form>")
print("</div>")
print("</div>")
print("</div>")
print("<div class='modal-footer'>")
print("<button type='button' class='btn btn-default'  onclick='close_modal()' data-dismiss='modal'> Close </button>")
print("</div>")
print("</div>")
print("</div>")
print("</div>")

###SIGN IN
print("<div class='modal' id='sign_in' role='dialog'>")
print("<div class='modal-dialog modal-lg'>")
print("<div class='modal-content' style='background: #000000;'>")
print("<div class='modal-header'>")
print("<button type='button' class='close' data-dismiss='modal'>&times;</button>")
print("<div class='row'>")
print("<div class='col-md-3'>")
print("<h4 class='modal-title'>")
print("<img src='images/logo.png' class='img-responsive' style='width: 15vw; height: 20vh; margin-left: 70%;'></h4>")
print("</div>")
print("<div class='col-md-9'>")
print("<h2 class='pull-right' style='color: #ffc80c; margin-top: %;'> Sign In</h2>")
print("</div>")
print("</div>")
print("</div>")
print("<div class='modal-body'>")
print("<div class='row'>")
print("<div class='col-md-6'>")
print("<form class='form-horizontal' role='form' action='customer_login.py'>")
print("<div class='form-group'>")
print("<label class='col-sm-3 control-label' for='email' style='color: white;'>Email <span style='color: red;'></span>")
print("</label>")
print("<div class='col-sm-9'>")
print("<input type='email' name='cemail' class='form-control' style='color:white;' id='cemail' placeholder='Your Email' required>")
print("</div>")
print("</div>")

print("<div class='form-group'>")
print("<label class='col-sm-3 control-label' for='pwd' style='color: white;'> Password:<span style='color: red;'></span>")
print("</label>")
print("<div class='col-sm-9'>")
print("<input type='password' class='form-control' id='cpwd' style='color:white;' name='cpwd' placeholder='Your Password' autofocus='' required>")
print("</div>")
print("</div>")
print("<div class='form-group'>")
print("<div class='text-center'>")
print("<input type='submit' class='btn btn-success btn-sm' value='Submit' style='margin-left: 27%; margin-top: %;'>")
print("</div>")
print("</div>")
print("</form>")
print("</div>")
print("</div>")
print("</div>")
print("<div class='modal-footer'>")
print("<button type='button' class='btn btn-default'  onclick='close_modal()' data-dismiss='modal'> Close </button>")
print("</div>")
print("</div>")
print("</div>")
print("</div>")
